default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

  # Important configs for cloud9, change password value
  # to what you entered in the previous psql step.
  #template: template0
  #username: ubuntu
  #password: password

development:
  <<: *default
  database: youtube_development
  username: postgres
  password: Cloud7831

test:
  <<: *default
  database: youtube_test
  username: postgres
  password: Cloud7831

production:
  <<: *default
  database: youtube_production
  username: youtube
  password: <%= ENV['password'] %>
